name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t secure-company-portal .

      - name: Run container (test)
        run: docker run -d -p 8080:80 secure-company-portal
