name: Secure CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Secrets Scan
      - name: Gitleaks Scan
        uses: zricethezav/gitleaks-action@v2

      # 2. Code Security Scan
      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      # 3. Build & Scan Backend Image
      - name: Build Backend Image
        run: docker build -f Dockerfile.backend -t secure-backend .

      - name: Trivy Scan Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-backend
          format: table
          severity: CRITICAL,HIGH

      # 4. Build & Scan Frontend Image
      - name: Build Frontend Image
        run: docker build -f Dockerfile.frontend -t secure-frontend .

      - name: Trivy Scan Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-frontend
          format: table
          severity: CRITICAL,HIGH
